# My travis file
language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ashishgarwal/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true ashishgarwal/docker-react npm run test -- --coverage

deploy:
  provier: elasticbeanstalk
  region: "ap-south-1"
  app: "MyWebApp"
  env: "Mywebapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-853673960985"
  bucket_path:  "MyWebApp"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
