# My travis file
language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ashishgarwal/docker-react -f Dockerfile .

script:
  - docker run  -e CI=true ashishgarwal/docker-react npm run test -- --coverage

deploy:
  provier: elasticbeanstalk
  region: "us-east-1"
  app: "My Web App"
  env: "MyWebApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-853673960985"
  bucket_path:  "My Web App"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
