language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ashishgarwal/docker-react -f Dockerfile.dev .

script:
  - docker run  ashishgarwal/docker-react npm run test -- --coverage
